apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-deployment
  labels:
    app: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - name: petstore
          image: nahid0002/petstore:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: petstore-svc
spec:
  selector:
    app: petstore
  ports:
    - name: http
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalance # Change this according to your environment (NodePort, LoadBalancer, etc.)